from typing import Any

from handlers.commissions_handlers import build_commissions_route_handlers
from repositories.commission_repository import (
    delete_commission_rule_by_id as _delete_commission_rule_by_id_repo,
    find_agency_by_id as _find_agency_by_id_commission_repo,
    find_brand_by_id as _find_brand_by_id_commission_repo,
    find_commission_closure_by_id as _find_commission_closure_by_id_repo,
    find_commission_closure_by_scope as _find_commission_closure_by_scope_repo,
    find_commission_matrix_by_agency as _find_commission_matrix_by_agency_repo,
    find_commission_rule_by_id as _find_commission_rule_by_id_repo,
    find_group_by_id as _find_group_by_id_commission_repo,
    find_user_by_id as _find_user_by_id_commission_repo,
    insert_commission_closure as _insert_commission_closure_repo,
    insert_commission_rule as _insert_commission_rule_repo,
    list_active_rules_by_agency,
    list_commission_closures as _list_commission_closures_repo,
    list_commission_rules as _list_commission_rules_repo,
    list_sales_for_closure as _list_sales_for_closure_repo,
    update_commission_closure_by_id as _update_commission_closure_by_id_repo,
    update_commission_rule_by_id as _update_commission_rule_by_id_repo,
    upsert_commission_matrix_by_agency as _upsert_commission_matrix_by_agency_repo,
)
from services.commission_management_service import (
    build_commission_approval_update_fields as _build_commission_approval_update_fields_service,
    build_commission_closure_doc as _build_commission_closure_doc_service,
    build_commission_closure_snapshot as _build_commission_closure_snapshot_service,
    build_commission_matrix_upsert_fields as _build_commission_matrix_upsert_fields_service,
    build_commission_rule_doc as _build_commission_rule_doc_service,
    build_commission_rule_update_fields as _build_commission_rule_update_fields_service,
    build_commission_simulator_projection as _build_commission_simulator_projection_service,
    build_month_bounds as _build_month_bounds_service,
    normalize_commission_status as _normalize_commission_status_service,
)
from services.commission_service import calculate_commission_from_rules as _calculate_commission_from_rules


def build_commissions_route_handler_bundle(
    *,
    db,
    get_current_user,
    object_id_cls,
    ensure_doc_scope_access,
    log_audit_event,
    serialize_doc,
    build_scope_query,
    scope_query_has_access,
    validate_scope_filters,
    normalize_commission_matrix_general,
    normalize_commission_matrix_models,
    get_catalog_models_for_brand,
    build_matrix_models_response,
    to_non_negative_float,
    commission_matrix_editor_roles,
    commission_proposer_roles,
    commission_approver_roles,
    commission_pending: str,
    commission_approved: str,
    commission_rejected: str,
    dealer_sales_effective_roles,
    dealer_general_effective_roles,
    dealer_seller_role,
    seller_role: Any,
):
    return build_commissions_route_handlers(
        db=db,
        get_current_user=get_current_user,
        object_id_cls=object_id_cls,
        ensure_doc_scope_access=ensure_doc_scope_access,
        log_audit_event=log_audit_event,
        serialize_doc=serialize_doc,
        build_scope_query=build_scope_query,
        scope_query_has_access=scope_query_has_access,
        validate_scope_filters=validate_scope_filters,
        normalize_commission_matrix_general=normalize_commission_matrix_general,
        normalize_commission_matrix_models=normalize_commission_matrix_models,
        get_catalog_models_for_brand=get_catalog_models_for_brand,
        build_matrix_models_response=build_matrix_models_response,
        to_non_negative_float=to_non_negative_float,
        normalize_commission_status=_normalize_commission_status_service,
        commission_matrix_editor_roles=commission_matrix_editor_roles,
        commission_proposer_roles=commission_proposer_roles,
        commission_approver_roles=commission_approver_roles,
        commission_pending=commission_pending,
        commission_approved=commission_approved,
        commission_rejected=commission_rejected,
        dealer_sales_effective_roles=dealer_sales_effective_roles,
        dealer_general_effective_roles=dealer_general_effective_roles,
        dealer_seller_role=dealer_seller_role,
        seller_role=seller_role,
        find_agency_by_id=_find_agency_by_id_commission_repo,
        find_brand_by_id=_find_brand_by_id_commission_repo,
        find_group_by_id=_find_group_by_id_commission_repo,
        find_user_by_id=_find_user_by_id_commission_repo,
        find_commission_matrix_by_agency=_find_commission_matrix_by_agency_repo,
        upsert_commission_matrix_by_agency=_upsert_commission_matrix_by_agency_repo,
        build_commission_matrix_upsert_fields=_build_commission_matrix_upsert_fields_service,
        build_commission_rule_doc=_build_commission_rule_doc_service,
        insert_commission_rule=_insert_commission_rule_repo,
        list_commission_rules=_list_commission_rules_repo,
        find_commission_rule_by_id=_find_commission_rule_by_id_repo,
        build_commission_rule_update_fields=_build_commission_rule_update_fields_service,
        update_commission_rule_by_id=_update_commission_rule_by_id_repo,
        build_commission_approval_update_fields=_build_commission_approval_update_fields_service,
        delete_commission_rule_by_id=_delete_commission_rule_by_id_repo,
        list_active_rules_by_agency=list_active_rules_by_agency,
        build_commission_simulator_projection=_build_commission_simulator_projection_service,
        calculate_commission_from_rules=_calculate_commission_from_rules,
        build_month_bounds=_build_month_bounds_service,
        list_sales_for_closure=_list_sales_for_closure_repo,
        build_commission_closure_snapshot=_build_commission_closure_snapshot_service,
        find_commission_closure_by_scope=_find_commission_closure_by_scope_repo,
        build_commission_closure_doc=_build_commission_closure_doc_service,
        update_commission_closure_by_id=_update_commission_closure_by_id_repo,
        find_commission_closure_by_id=_find_commission_closure_by_id_repo,
        insert_commission_closure=_insert_commission_closure_repo,
        list_commission_closures=_list_commission_closures_repo,
    )


__all__ = ["build_commissions_route_handler_bundle"]
