from handlers.dashboard_handlers import build_dashboard_route_handlers
from repositories.dashboard_repository import (
    count_sales as _count_sales_dashboard_repo,
    count_users as _count_users_dashboard_repo,
    find_user_by_id as _find_user_by_id_dashboard_repo,
    list_agencies_by_brand_id as _list_agencies_by_brand_id_dashboard_repo,
    list_agencies_by_group_id as _list_agencies_by_group_id_dashboard_repo,
    list_global_monthly_closes_by_year,
    list_sales as _list_sales_dashboard_repo,
    list_sales_objectives as _list_sales_objectives_dashboard_repo,
    list_vehicles as _list_vehicles_dashboard_repo,
    list_vehicles_by_ids as _list_vehicles_by_ids_dashboard_repo,
    upsert_global_monthly_close,
)
from services.dashboard_service import (
    build_dashboard_monthly_close_calendar as _build_dashboard_monthly_close_calendar_service,
    build_dashboard_monthly_close_response as _build_dashboard_monthly_close_response_service,
    collect_vehicle_suggestions as _collect_vehicle_suggestions_service,
    compute_dashboard_kpis as _compute_dashboard_kpis_service,
    compute_sales_trends as _compute_sales_trends_service,
    compute_seller_performance as _compute_seller_performance_service,
    empty_dashboard_kpis_response as _empty_dashboard_kpis_response_service,
)
from services.operational_calendar_service import (
    compute_operational_day_profile as _compute_operational_day_profile,
    decrement_month as _decrement_month,
    mexico_lft_holidays_by_month as _mexico_lft_holidays_by_month,
    resolve_effective_objective_units as _resolve_effective_objective_units,
)


def build_dashboard_route_handler_bundle(
    *,
    db,
    get_current_user,
    validate_scope_filters,
    build_scope_query,
    scope_query_has_access,
    resolve_dashboard_scope_group_id,
    find_dashboard_monthly_close,
    add_months_ym,
    log_audit_event,
    app_admin_role,
    user_role_seller,
    enrich_vehicle,
    calculate_vehicle_financial_cost_in_period,
    sale_effective_revenue,
    objective_approved: str,
    objective_pending: str,
    coerce_utc_datetime,
    build_vehicle_aging_suggestion,
):
    return build_dashboard_route_handlers(
        db=db,
        get_current_user=get_current_user,
        validate_scope_filters=validate_scope_filters,
        build_scope_query=build_scope_query,
        scope_query_has_access=scope_query_has_access,
        resolve_dashboard_scope_group_id=resolve_dashboard_scope_group_id,
        find_dashboard_monthly_close=find_dashboard_monthly_close,
        build_dashboard_monthly_close_response=_build_dashboard_monthly_close_response_service,
        mexico_lft_holidays_by_month=_mexico_lft_holidays_by_month,
        list_global_monthly_closes_by_year=list_global_monthly_closes_by_year,
        build_dashboard_monthly_close_calendar=_build_dashboard_monthly_close_calendar_service,
        upsert_global_monthly_close=upsert_global_monthly_close,
        add_months_ym=add_months_ym,
        log_audit_event=log_audit_event,
        app_admin_role=app_admin_role,
        user_role_seller=user_role_seller,
        empty_dashboard_kpis_response=_empty_dashboard_kpis_response_service,
        compute_dashboard_kpis=_compute_dashboard_kpis_service,
        list_vehicles=_list_vehicles_dashboard_repo,
        list_sales=_list_sales_dashboard_repo,
        list_vehicles_by_ids=_list_vehicles_by_ids_dashboard_repo,
        list_agencies_by_brand_id=_list_agencies_by_brand_id_dashboard_repo,
        list_agencies_by_group_id=_list_agencies_by_group_id_dashboard_repo,
        count_users=_count_users_dashboard_repo,
        count_sales=_count_sales_dashboard_repo,
        enrich_vehicle=enrich_vehicle,
        calculate_vehicle_financial_cost_in_period=calculate_vehicle_financial_cost_in_period,
        sale_effective_revenue=sale_effective_revenue,
        compute_sales_trends=_compute_sales_trends_service,
        objective_approved=objective_approved,
        objective_pending=objective_pending,
        list_sales_objectives=_list_sales_objectives_dashboard_repo,
        coerce_utc_datetime=coerce_utc_datetime,
        decrement_month=_decrement_month,
        compute_operational_day_profile=_compute_operational_day_profile,
        resolve_effective_objective_units=_resolve_effective_objective_units,
        compute_seller_performance=_compute_seller_performance_service,
        find_user_by_id=_find_user_by_id_dashboard_repo,
        collect_vehicle_suggestions=_collect_vehicle_suggestions_service,
        build_vehicle_aging_suggestion=build_vehicle_aging_suggestion,
    )


__all__ = ["build_dashboard_route_handler_bundle"]
